[package]
name= 'music-player'
version= '0.0.0'
authors= ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition= '2018'

[dependencies]
anyhow= ''
fehler= ''
futures-lite= ''
futures-util= ''
walkdir= ''
alsa= ''
symphonia= {features= ['mp3'], version= ''}
ui= {git='https://github.com/Matthias-Fauconneau/ui'}
async-io= ''
zbus= {git='https://gitlab.freedesktop.org/matthias.fauconneau/zbus', branch='main'}
