[package]
name= 'music-player'
version= '0.0.0'
authors= ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition= '2018'

[dependencies]
derive_more= ''
anyhow= ''
fehler= ''
futures-lite= ''
walkdir= ''
alsa= ''
symphonia= {features= ['mp3'], version= ''}
ui= {path='../ui'}#git='https://github.com/Matthias-Fauconneau/ui'}
async-io= ''
